server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: report-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/reports/**
        - id: business-metadata-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/business-metadata/**
        - id: data-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/data/**,/api/adjustments/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
