server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "*"
        - id: report-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/reports/**
          filters:
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "*"
        - id: business-metadata-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/business-metadata/**
          filters:
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "*"
        - id: data-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/data/**,/api/adjustments/**
          filters:
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "*"
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
