server:
  port: 8083

spring:
  application:
    name: data-service
  datasource:
    url: jdbc:postgresql://localhost:5432/datadb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
